Repository hc-sc-ocdo-bdpd/file-processing-tools, pull requests merged in 2023-08, with the labels that each got.

#23 Critical fix of the table assembly
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/table_tools.py
  tests/resources/simple_table.PNG
  tests/table_test.py
Labels: bug, enhancement

#25 Extract Table Contents test case
  generated_tables/DmZUHweaZfPcMjTCAySRtp.pdf
  generated_tables/GBnzszrSV2sAXLEH5k7SFz.pdf
  table_processing/TableMetrics.ipynb
  table_processing/benchmark_pipeline.py
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V.pdf
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V.xlsx
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V_boxes.jpg
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V_true.xlsx
  tests/table_test.py
Labels: bug, enhancement

#26 added test cases for row and column
  table_processing/Table.py
  tests/generatedtable_test.py
  tests/resources/DmZUHweaZfPcMjTCAySRtp.pdf
  tests/resources/GBnzszrSV2sAXLEH5k7SFz.pdf
  tests/table_test.py
Labels: bug, enhancement

#35 Various QoL changes and OCR output fix
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/benchmark_pipeline.py
  table_processing/table_tools.py
  tests/table_test.py
Labels: bug

#39 added new test cases
  table_processing/Table.py
  tests/table_test.py
Labels: enhancement

#47 Remove separator character at start and end of string ("|")
  table_processing/Table.py
Labels: bug

#49 made font_size work
  table_processing/GeneratedTable.py
  table_processing/benchmark_pipeline.py
Labels: enhancement

#50 Checked if packages are necessary
  requirements.txt
Labels: enhancement

#46 Fix to the overflowing of tables off the page
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/TableMetrics.ipynb
  table_processing/benchmark_pipeline.py
  table_processing/table_metrics.py
Labels: bug

#45 Update README
  README.md
Labels: documentation

#53 Fix to the general table box being cropped too close to its borders
  table_processing/Table_Detector.py
  table_processing/benchmark_pipeline.py
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V.pdf
  tests/resources/MknamLBhTbMkiPABhMhN5V/MknamLBhTbMkiPABhMhN5V_boxes.jpg
  tests/resources/test_extract_table_content/test_extract_table_content.pdf
  tests/resources/test_extract_table_content/test_extract_table_content_true.xlsx
  tests/resources/test_metrics/test_metrics.xlsx
  tests/resources/test_metrics/test_metrics_true.xlsx
  tests/table_test.py
Labels: bug

#59 A console application that the client could use
  table_processing/Table_processor_main.py
Labels: enhancement

#61 Added parameter tracking in table_metrics output sheet
  table_processing/GeneratedTable.py
  table_processing/benchmark_pipeline.py
Labels: enhancement

#62 Added bullet proofing to the main console application
  table_processing/Table_processor_main.py
  tests/table_test.py
Labels: bug

#64 Randomized trial results & location metrics error fixed
  README.md
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/TableMetrics.ipynb
  table_processing/metrics_results.py
  table_processing/table_metrics.py
  table_trials_results/table_metrics_ALL.xlsx
  table_trials_results/table_metrics_fontsize.xlsx
  table_trials_results/table_metrics_lines.xlsx
  table_trials_results/table_metrics_margin.xlsx
  table_trials_results/table_metrics_portrait-landscape.xlsx
  table_trials_results/table_metrics_row-height.xlsx
  table_trials_results/table_metrics_rows-cols.xlsx
  table_trials_results/table_metrics_special-characters.xlsx
Labels: bug, enhancement

#63 Basic GUI
  .gitignore
  README.md
  requirements.txt
  table_processing/GUI.py
  table_processing/Table_Detector.py
  table_processing/Table_processor_main.py
  tests/table_test.py
Labels: enhancement

#70 Documentation, test results, & full randomization of generated tables
  README.md
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/TableMetrics.ipynb
  table_processing/Table_Detector.py
  table_processing/Table_processor_main.py
  table_processing/benchmark_pipeline.py
  table_processing/metrics_results.py
  table_processing/table_metrics.py
  table_trials_results/first_run/table_metrics_ALL.xlsx
  table_trials_results/first_run/table_metrics_fontsize.xlsx
  table_trials_results/first_run/table_metrics_lines.xlsx
  table_trials_results/first_run/table_metrics_margin.xlsx
  table_trials_results/first_run/table_metrics_portrait-landscape.xlsx
  table_trials_results/first_run/table_metrics_row-height.xlsx
  table_trials_results/first_run/table_metrics_rows-cols.xlsx
  table_trials_results/first_run/table_metrics_special-characters.xlsx
  table_trials_results/table_metrics_1-1500.xlsx
  table_trials_results/table_metrics_1501-2000.xlsx
  table_trials_results/table_metrics_2001-3500.xlsx
  table_trials_results/table_metrics_3501-5000.xlsx
  table_trials_results/table_metrics_ALL.xlsx
Labels: documentation, enhancement

#72 Adding intermediate outputs
  table_processing/Table_Detector.py
  table_processing/Table_processor_main.py
  table_processing/benchmark_pipeline.py
Labels: enhancement

#73 Table OCR Refactor
  table_processing/Table.py
  table_processing/table_tools.py
  tests/table_test.py
Labels: enhancement

#75 Added Plotting of all tables in each page
  table_processing/Table.py
  table_processing/Table_Detector.py
  table_processing/Table_processor_main.py
  tests/table_test.py
Labels: enhancement
