Repository hc-sc-ocdo-bdpd/file-processing-tools, pull requests merged in 2023-07, with the labels that each got.

#2 Removed gitlab artifact
  .gitlab-ci.yml
Labels: enhancement

#1 MVP for table data extraction
  requirements.txt
  table_processing/Table.py
  table_processing/Table_Detector.py
  table_processing/table_tools.py
  tests/table_test.py
Labels: enhancement

#17 Fixed issue with missing directory
  table_processing/GeneratedTable.py
Labels: bug

#18 Bounding box plot
  .gitignore
  table_processing/Table.py
  table_processing/benchmark_pipeline.py
Labels: bug, help wanted

#16 margin/multirow params
  table_processing/GeneratedTable.py
Labels: enhancement

#19 Adding Metrics Pipeline
  .gitignore
  requirements.txt
  table_processing/GeneratedTable.py
  table_processing/Table.py
  table_processing/TableMetrics.ipynb
  table_processing/Table_Detector.py
  table_processing/benchmark_pipeline.py
  table_processing/table_metrics.py
Labels: enhancement

#21 Path-related errors fixed
  table_processing/GeneratedTable.py
  table_processing/benchmark_pipeline.py
Labels: bug
